In [57]:
import numpy as np
from distributed.protocol.numpy import itemsize

In [58]:
arr1 = np.arange(15).reshape(3,5)

In [64]:
print(arr1)
print(arr1.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
4


In [66]:
print(arr1.dtype)# int32 数组元素的数据类型

int32


In [68]:
print(arr1.shape)# (3, 5)数组形状

(3, 5)


In [70]:
print(arr1.size)#矩阵元素个数15

15


In [73]:
print(arr1.ndim)# 打印出2,代表二维数组

2
