In [3]:
import numpy as np


In [ ]:
# 传入列表创建ndarry
list_a = [11,22,33]
arr1 = np.array(list_a)
print(arr1)
print(type(arr1))

In [ ]:
# 用arange方法创建数组
arr2 = np.arange(0,10,2,dtype=np.int64)
print(arr2)
print(type(arr2))  # <class 'numpy.ndarray'>

In [ ]:
# 用random.rand方法随机生成多维数组
arr3 = np.random.rand(3,4) # 生成一个三行四列,范围在[0,1)之间的矩阵
print(arr3)
print(type(arr3))

In [4]:
# 用random.randint生成多维整形数组
arr4 = np.random.randint(0,10,(3,4))# 生成一个范围是[0,10) 三行四列的数组
print(arr4)
print(type(arr4))

[[3 7 7 1]
 [8 6 2 2]
 [9 3 5 1]]
<class 'numpy.ndarray'>


In [ ]:
# 用random.uniform生成多维浮点数数组
arr5 = np.random.uniform(0,10,(3,4))# 范围[0,10)形状3行4列
print(arr5)
print(type(arr5))

In [1]:
# 试一试random.randn
arr6 = np.random.randn(3,4)
print(arr6)

NameError: name 'np' is not defined

In [ ]:
# 改变数组类型
arr7 = np.arange(0,10,dtype=np.int64)
print(arr7)
print(arr7.dtype)
arr7 = arr7.astype(np.float64) # astype方法改变dtype元素类型为float64
print(arr7)
print(arr7.dtype)

In [28]:
# 等比和等差数列
arr8 = np.logspace(0,3,4) # 按照10的指数从0开始(10的0次幂)到3(10的三次幂)结束
print(arr8)
print(type(arr8))

arr9 = np.linspace(0,10,10)
print(arr9)
print(type(arr9))

[   1.   10.  100. 1000.]
<class 'numpy.ndarray'>
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
<class 'numpy.ndarray'>


In [35]:
# numpy内置函数
arr10 = np.random.randn(3,5)
print(arr10)
print(np.ceil(arr10))
print(np.floor(arr10))
print(np.abs(arr10))
print(np.rint(arr10))
print(np.multiply(arr10,arr10))
print(np.divide(arr10,arr10))
print(np.where(arr10>1,1,0))

[[-0.77977727 -0.2641529  -0.98536401 -1.56814018 -1.42546731]
 [ 0.79407437 -0.98335432 -0.91366428  0.46708528 -0.51547548]
 [ 1.40851518 -0.37374826  1.75136746 -1.12335543  0.03399092]]
[[-0. -0. -0. -1. -1.]
 [ 1. -0. -0.  1. -0.]
 [ 2. -0.  2. -1.  1.]]
[[-1. -1. -1. -2. -2.]
 [ 0. -1. -1.  0. -1.]
 [ 1. -1.  1. -2.  0.]]
[[0.77977727 0.2641529  0.98536401 1.56814018 1.42546731]
 [0.79407437 0.98335432 0.91366428 0.46708528 0.51547548]
 [1.40851518 0.37374826 1.75136746 1.12335543 0.03399092]]
[[-1. -0. -1. -2. -1.]
 [ 1. -1. -1.  0. -1.]
 [ 1. -0.  2. -1.  0.]]
[[6.08052584e-01 6.97767555e-02 9.70942241e-01 2.45906364e+00
  2.03195706e+00]
 [6.30554099e-01 9.66985723e-01 8.34782423e-01 2.18168658e-01
  2.65714975e-01]
 [1.98391501e+00 1.39687760e-01 3.06728797e+00 1.26192742e+00
  1.15538231e-03]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 1 0 0]]


In [48]:
# np统计函数
arr1 = np.arange(1,13,dtype=np.int64).reshape(3,4)
print(arr1)
print(np.sum(arr1))
print(np.sum(arr1,axis=0))
print(np.sum(arr1,axis=1))
print(np.argmax(arr1))
print(np.argmin(arr1))
print(np.cumsum(arr1))
print(np.cumprod(arr1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]
11
0
[ 1  3  6 10 15 21 28 36 45 55 66 78]
[        1         2         6        24       120       720      5040
     40320    362880   3628800  39916800 479001600]


In [52]:
# 数组去重和排序
arr2 = np.array([[1,3,2],[4,9,3]])
arr2_un = np.unique(arr2)
print(arr2_un)

arr2 = np.array([[1,3,2,7,5,9,1]])
arr2_sort = np.sort(arr2)
print(arr2_sort)


[1 2 3 4 9]
[[1 1 2 3 5 7 9]]


In [54]:
# 矩阵相乘(行列数不一致)
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],
                 [3,4],
                 [5,6]])
# 方法一
print(arr1@arr2)
# 方法二
print(np.dot(arr1,arr2))
print(arr1.dot(arr2))

[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
