In [8]:
# 导包
import pandas as pd
import numpy as np

使用 `np.arange()` 创建一个从 0 到 9（包含 0，不包含 10）的一维数组。

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

使用 `np.arange()` 创建一个从 5 到 20（步长为 3）的数组。

In [10]:
np.arange(5,20,3)

array([ 5,  8, 11, 14, 17])

创建一个 3×4 的二维数组，并打印其 `shape`。

In [12]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

给定数组 `a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])`，打印它的 `shape`。

In [13]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a.shape)

(2, 2, 2)


创建一个整数数组 `[1, 2, 3]`，并打印其数据类型

In [16]:
print(np.arange(1,4).dtype)

int32


创建一个浮点数组，并显式指定 `dtype` 为 `np.float32`，然后打印其 `dtype`。

In [19]:
print(np.arange(1,4,dtype=np.float32).dtype)

float32


创建一个标量（0 维）数组 `np.array(5)`，并打印其维度数。

In [20]:
print(np.array(5).ndim)

0


创建一个三维数组 `np.ones((2, 3, 4))`，并打印其 `ndim`。

In [21]:
print(np.ones((2,3,4)).ndim)

3


给定数组 `a = np.array([3, 1, 4, 1, 5, 9, 2])`，找出最大值的索引。

In [22]:
a = np.array([3, 1, 4, 1, 5, 9, 2])
np.argmax(a)

5

给定二维数组 `b = np.array([[1, 2, 3], [6, 5, 4]])`，找出每列最大值的行索引

In [29]:
b = np.array([[1, 2, 3], [6, 5, 4]])
for i in range(b.shape[0]):
    print(f'第{i+1}行最大值索引为{np.argmax(b[i])}')

第1行最大值索引为2
第2行最大值索引为0


对数组 `c = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])` 去重并排序（使用 `np.unique`）。

In [34]:
c = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print(np.unique(c))
print(c)


[1 2 3 4 5 6 9]
[3 1 4 1 5 9 2 6 5]


对数组 `d = np.array([9, 3, 7, 1])` 进行升序排序（使用 `np.sort`），并保留原数组不变。

In [33]:
d = np.array([9, 3, 7, 1])
print(np.sort(d))
print(d)

[1 3 7 9]
[9 3 7 1]


创建一个 2×3 的矩阵 A 和一个 3×2 的矩阵 B，计算 `A @ B`

In [41]:
a = np.random.randint(0,6,(2,3))
b = np.random.randint(0,6,(3,2))
print(a@b)

[[23 17]
 [10 26]]


尝试用 `@` 计算两个不能相乘的矩阵（如 2×3 和 2×2），观察报错信息。

In [43]:
a = np.random.randint(0,6,(2,3))
b = np.random.randint(0,6,(2,2))
print(a@b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

创建一个包含三列数值数据的 DataFrame（例如：`'A': [1, 2, 3, 4]`, `'B': [10, 20, 30, 40]`, `'C': [100, 200, 300, 400]`），并调用 `.describe()` 查看统计摘要。

In [45]:
data_d = {'A': [1, 2, 3, 4], 'B': [10, 20, 30, 40], 'C': [100, 200, 300, 400]}
df = pd.DataFrame(data_d)
print(df)
df.describe()

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400


A          B           C
count  4.000000   4.000000    4.000000
mean   2.500000  25.000000  250.000000
std    1.290994  12.909944  129.099445
min    1.000000  10.000000  100.000000
25%    1.750000  17.500000  175.000000
50%    2.500000  25.000000  250.000000
75%    3.250000  32.500000  325.000000
max    4.000000  40.000000  400.000000

创建一个包含缺失值的 DataFrame（例如：`'X': [1, 2, None]`, `'Y': ['a', None, 'c']`），调用 `.info()` 查看各列的数据类型和非空计数。

In [46]:
df2 = pd.DataFrame({'X': [1, 2, None], 'Y': ['a', None, 'c']})
df2.info

<bound method DataFrame.info of      X     Y
0  1.0     a
1  2.0  None
2  NaN     c>

创建一个 2 行 3 列的 DataFrame，使用 `.T` 转置它，并打印原始和转置后的结果。

In [49]:
df3 = pd.DataFrame(([1,2],[3,4],[5,6]))
print(df3)
df3.T

   0  1
0  1  2
1  3  4
2  5  6


0  1  2
0  1  3  5
1  2  4  6